version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: "PE2ghI_19Bl1ChCENSM7xmuxM46mVK1z"
    volumes:
      - todos_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "2klPuHsP5sIVJOFupY71NUr9TLF52pAt"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  todos_data:
